version: "3.7"
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - spring-ecommerce

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      spring-ecommerce:
        aliases:
          - zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      spring-ecommerce:
        aliases:
          - kafka

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    depends_on:
      - kafka
    ports:
      - 9091:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
    networks:
      spring-ecommerce:
        aliases:
          - kafka-manager
  kafka-ui:
    image: docker.redpanda.com/vectorized/console:master-0a8fce8
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - 8081:8080
    networks:
      spring-ecommerce:
        aliases:
          - kafka-ui
networks:
  spring-ecommerce:
    external: true
volumes:
  my-db: null